# Generated by Django 3.2 on 2021-07-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_sku', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Accesories', 'Accesories'), ('Footwear', 'Footwear')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('percentage_discount', models.CharField(blank=True, max_length=4, null=True)),
                ('tag', models.CharField(blank=True, choices=[('Hot', 'Hot'), ('New', 'New')], max_length=10, null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('in_stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='banner_images/')),
                ('title_text', models.CharField(max_length=200)),
                ('special_text', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation_text', models.TextField(blank=True, max_length=300, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Featured Products',
            },
        ),
    ]
