# Generated by Django 3.2 on 2021-06-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Accesories', 'Accesories'), ('Footwear', 'Footwear')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('percentage_discount', models.CharField(blank=True, max_length=4, null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('in_stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
