# Generated by Django 3.2 on 2021-07-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210703_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredproduct',
            options={'verbose_name_plural': 'Featured Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.CharField(default='<built-in method now of type object at 0x00007FFFB901E550>', max_length=50),
        ),
    ]
