# Generated by Django 3.2 on 2021-07-03 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210703_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(default=datetime.datetime(2021, 7, 3, 15, 0, 55, 200526), max_length=50),
        ),
    ]
