# Generated by Django 3.2 on 2021-07-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(default='2021-07-03 15:02:01.603460', max_length=50),
        ),
    ]
